apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kless-server
  namespace: KLESS_NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      name: kless-server
      namespace: KLESS_NAMESPACE
      labels:
        app: kless-server
    spec:
      containers:
      - name: kless-server
        image: KLESS_DEST_REGISTRY_HOSTPORTklessv1/klessserver:BUILD_ID
        imagePullPolicy: Always
        env:
          - name: SERVER_NAMESPACE
            value: "KLESS_NAMESPACE"
          - name: REGISTRY_USERNAME
            value: "KLESS_DEST_REGISTRY_USERNAME"
          - name: REGISTRY_PASSWORD
            value: "KLESS_DEST_REGISTRY_PASSWORD"
          - name: REGISTRY_HOSTPORT
            value: "KLESS_DEST_REGISTRY_HOSTPORT"
        ports:
        - containerPort: 50051
          name: api
          protocol: TCP
        - containerPort: 8010
          name: etcd
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kless
    task: apiserver
  name: kless-server
  namespace: KLESS_NAMESPACE
spec:
  ports:
    - name: api
      port: 50051
      protocol: TCP
    - name: etcd
      port: 8010
      protocol: TCP
  selector:
    app: kless-server
  type: NodePort

