apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kless-registry
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: kless-registry
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: kless-registry-pvc        
