apiVersion: v1
kind: ReplicationController
metadata:
  name: kless-grafana
  namespace: KLESS_NAMESPACE
  labels: 
    k8s-app: grafana
spec: 
  replicas: 1
  selector: 
    k8s-app: grafana
  template: 
    metadata: 
      labels: 
        k8s-app: grafana
    spec: 
      containers: 
        - image: KLESS_SRC_REGISTRY/grafana/grafana:3.1.1
          name: grafana
          env:
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            # This variable is required to setup templates in Grafana.
            - name: INFLUXDB_SERVICE_URL
              value: http://kless-influxdb.KLESS_NAMESPACE:8086
              # The following env variables are required to make Grafana accessible via
              # the kubernetes api-server proxy. On production clusters, we recommend
              # removing these env variables, setup auth for grafana, and expose the grafana
              # service using a LoadBalancer or a public IP.
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
#            - name: GF_SERVER_ROOT_URL
#              value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
          volumeMounts:
          - name: grafana-persistent-storage
            mountPath: /var
      volumes:
      - name: grafana-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kless
    task: visualization
  name: kless-grafana
  namespace: KLESS_NAMESPACE
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    k8s-app: grafana
  type: NodePort

