kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kless-etcd-pvc
  namespace: KLESS_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kless-etcd
  namespace: KLESS_NAMESPACE
  labels:
    k8s-app: kless-etcd
spec:
  replicas: 1
  template:
    metadata:
      name: kless-etcd
      namespace: KLESS_NAMESPACE
      labels:
        k8s-app: kless-etcd
    spec:
      containers:
      - name: etcd
        image: KLESS_SRC_REGISTRY_QUAY/coreos/etcd:v3.2.9
        volumeMounts:
        - name: datadir
          mountPath: /var/run/etcd
        command:
          - "/bin/sh"
          - "-ec"
          - |
            IP=$(hostname -i)

            exec etcd --name node1 \
                --listen-peer-urls http://${IP}:2380 \
                --listen-client-urls http://0.0.0.0:2379 \
                --advertise-client-urls http://${IP}:2379 \
                --data-dir /var/run/etcd/default.etcd \
                --initial-advertise-peer-urls http://${IP}:2380 \
                --initial-cluster node1=http://${IP}:2380 
        ports:
        - containerPort: 2379
          name: etcd-client
          protocol: TCP
        - containerPort: 2380
          name: etcd-peer
          protocol: TCP
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: kless-etcd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kless-etcd
  namespace: KLESS_NAMESPACE
  labels:
    app: kless
    task: etcd
spec:
  selector:
    k8s-app: kless-etcd
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
  - name: etcd-peer
    port: 2380
    protocol: TCP
