apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    pdName: disk1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    pdName: disk2
    fsType: ext4
